spring.application.name=e-commerce
server.port=5454
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=Tanvi@2803

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#For sending email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luxorashop28@gmail.com
spring.mail.password=ddpc cxzq tlrr cchp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=uy9He2mP3Yz6FsqLrTjWqzCnAeW48VmX  # 32-char secret key


